### ISSUE TITLE
Access to default bean proccesing

### ISSUE THREAD

**Issue by jneira** [aalmiray/Json-lib#37]
Hi, when i try to register bean/value proccesor usually i need to rely on default proccesing to modify the default json on the fly, while keeping the rest of configuration. 
The problem is the default proccesing is not accesible from the custom proccesors (is in the private method JSONObject.defaultBeanProcessing)
To avoid circular calls i have to unregister proccesor/call fromObject with provided config/reregister proccesor, in the proccesor itself!
Maybe there is another more elegant way to get it
Thanks and congrats for the lib

**Comment by jneira** [comment]
In fact i have to use JsonValueProccesor to do the unregister/call fromObject/reregister
(cause _fromBean returns with handleRepeatedReferenceAsObject an empty json)
```
registerJsonValueProcessor(MyClass.class,
new JsonValueProcessor() {
  @Override
  public Object processArrayValue(Object arg0,JsonConfig arg1) {
    return processObjectValue(null,arg0,arg1);
  }
  @Override
  public Object processObjectValue(String arg0,Object arg1, JsonConfig arg2) {
    JsonValueProcessor prev=arg2.findJsonValueProcessor(MyClass.class)
    arg2.unregisterJsonValueProcessor(MyClass.class);
    try {
      JSONObject json=JSONObject.fromObject(arg1,arg2);
      modify(json);
    } finally {
      arg2.registerJsonValueProcessor(MyClass.class,prev);
    }
  }
})
```

**Comment by aalmiray** [comment]
Fixed with https://github.com/aalmiray/Json-lib/commit/3e89c35f6b7ce72fd5728cfd91dc7567bd082f8a

**Comment by aalmiray** [comment]
Please try the changes by building a local snapshot :smiley:

**Comment by jneira** [comment]
I've built the lib with two minor changes:
https://github.com/aalmiray/Json-lib/compare/master...jneira:master

**Comment by aalmiray** [comment]
At first I was surprised by the change but now I see what's going on. The latest version of the library (3.x) is being developed under the `development` branch. `master` branch contains the 2.x version which will no  longer be supported after 3.x comes out. The changes I made were posted to the `development` branch.

**Comment by jneira** [comment]
ops, I did not notice the branch name when I saw the commit

**Comment by jneira** [comment]
Finally i build dev branch (i had to delete guide subproject to avoid a "Could not find property compileOnly on configuration container." error) and tested the changes with https://gist.github.com/jneira/2adade4797c888946e7446babf720e04
Much better!
However, have you considered that default bean proccesing was in a (external?) class implementing  JsonBeanProcessor and register it as the default bean processor for Object?

**Comment by aalmiray** [comment]
The `compileOnly` configuration is added by Gradle as long as you use version 2.12 or greater. The project's Gradle wrapper has been set to 2.12

**Comment by jneira** [comment]
i have a lower version of gradle, thanks for the quick response and for the lib, i'll look forward the new realease
