### ISSUE TITLE
Problem with licensing

### ISSUE THREAD

**Issue by tdunning** [aalmiray/Json-lib#46]
Your library says that it includes code written by Douglas Crockford. That seems very likely to be the json.org json library.

That library had a license that is not Apache License compatible. Inclusion of that code would make your library incompatible with the Apache License.

I have a few questions and a suggestion:

1) is that the code you are referring to in your POM?

2) if so, can you clarify your license so that people don't misunderstand and think that your code is open source.

3) is it possible to switch your dependency to a library that has a valid open source license? I would offer https://github.com/tdunning/open-json as an example of such.

**Comment by aalmiray** [comment]
Json-lib is licensed under Apache 2.0
