### ISSUE TITLE
Would Json-lib keep in maintaining?

### ISSUE THREAD

**Issue by Alanscut** [aalmiray/json-lib#50]
Hi Andres @aalmiray , json-lib has been widely used in the past few years, although there are a lot of excellent JSON parse software available for developers to choose from, there are still many people who will continue to choose json-lib. In order to make json-lib users have better support, would you consider adding a collaborator to help you manage the community, handle some issues, fix bugs, even add some new features?

**Comment by Alanscut** [comment]
@aalmiray

**Comment by aalmiray** [comment]
I'm surprised developers still use Json-lib given that there are newer, faster alternatives such as Jackson, Gson, and fast-json. This being said, the `development` branch contains updates for the upcoming `3.x` release which is only missing upgrades to the documentation.

Stay tuned for a release soon.

**Comment by Alanscut** [comment]
Thank you for maintaining this software still. A new release will make sense!

**Comment by aalmiray** [comment]
Release `3.0.0` has been posted.
